version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: cleango
      POSTGRES_PASSWORD: cleango123
      POSTGRES_DB: cleango_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
