version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: cleango_postgres
    restart: always
    environment:
      POSTGRES_USER: cleango_user
      POSTGRES_PASSWORD: cleango_pass
      POSTGRES_DB: CleanGoDb
    ports:
      - "5432:5432"
    volumes:
      - cleango_postgres_data:/var/lib/postgresql/data

volumes:
  cleango_postgres_data:
